#---------------------------------
# External Dependencies:
# R2MLwiN
#
# Internal Dependencies:
# build_mm_list
#---------------------------------


#' run_mlwin
#'
#' @param .dat A dataframe produced by \code{\link{generate_data}}.
#'
#' @param .model_formula A formula object.
#' @param .outcome_dist A string. Defaults to "Normal".
#' @param .mcmc_burn Numeric. Defaults to 100.
#' @param .mcmc_iter Numeric. Defaults to 1000.
#' @param .mcmc_nchains Numeric. Defaults to 1.
#' @param .mm_list A list. Generated by \code{\list{build_mm_list}}
#'
#' @return Returns a model object produced by \code{\link[R2MLwiN]{runMLwiN}}.
#' @export
#'
#' @examples \dontrun{
#'
#' }
run_mlwin <-
  function(
    .dat,
    .model_formula = as.formula("y ~ 1 + (1 | sch_id_1) + (1 | stu_id)"),
    .outcome_dist = "Normal",
    .mcmc_burn = 100,
    .mcmc_iter = 1000,
    .mcmc_nchains = 1,
    .mm_list = NULL
  ) {

    ##--run model--##

    model_fit <-
      R2MLwiN::runMLwiN(
        .model_formula,
        D = .outcome_dist,
        estoptions = list(
          EstM = 1,
          mcmcMeth = list(
            burnin = .mcmc_burn,
            iterations = .mcmc_iter,
            nchains = .mcmc_nchains
          ),
          mm = .mm_list,
          resi.store = FALSE
        ),
        data = .dat
      )

    ##--output--##
    model_fit


  }


